/* tslint:disable */
/* eslint-disable */
import { ExportedEndpointDetailData } from '../models/exported-endpoint-detail-data';
import { ExportedFingerprintCollectionEntryData } from '../models/exported-fingerprint-collection-entry-data';
import { ExportedProbeData } from '../models/exported-probe-data';
import { ExportedPropertyDescriptor } from '../models/exported-property-descriptor';
import { ExportedReflectionData } from '../models/exported-reflection-data';
import { ExportedTrafficTemplateDefinitionSource } from '../models/exported-traffic-template-definition-source';
import { FindingStateEnum } from '../models/finding-state-enum';
import { FuzzWorkflowParameterData } from '../models/fuzz-workflow-parameter-data';
import { JsFrameworkData } from '../models/js-framework-data';
import { MatchWebRuleResults } from '../models/match-web-rule-results';
import { RuleBehaviorData } from '../models/rule-behavior-data';
import { RuleParameterData } from '../models/rule-parameter-data';
import { RuleTypeEnum } from '../models/rule-type-enum';
import { ServerFrameworkData } from '../models/server-framework-data';
import { SeverityEnum } from '../models/severity-enum';
import { TrafficSequenceData } from '../models/traffic-sequence-data';
import { VariableData } from '../models/variable-data';
import { WorkflowActionData } from '../models/workflow-action-data';
import { WorkflowParameterData } from '../models/workflow-parameter-data';
export interface ExportedFindingData {
  ActionData?: WorkflowActionData;
  Behaviors?: Array<RuleBehaviorData> | null;
  ChildWorkflows?: Array<string> | null;
  CollectionEntry?: ExportedFingerprintCollectionEntryData;
  Comment?: string | null;
  DefaultSort?: string | null;
  DocumentHtml?: string | null;
  EndpointDetail?: ExportedEndpointDetailData;
  FoundDateTime?: string | null;
  FoundMatchResults?: MatchWebRuleResults;
  Frameworks?: Array<JsFrameworkData> | null;
  FuzzMatch?: MatchWebRuleResults;
  FuzzWorkflowParameters?: Array<FuzzWorkflowParameterData> | null;
  JobUniqueID?: string | null;
  LoginWorkflowText?: string | null;
  LogoutWorkflowText?: string | null;
  Name?: string | null;
  ParentTraffic?: Array<TrafficSequenceData> | null;
  Probe?: ExportedProbeData;
  ProbeGroupID?: string | null;
  Properties?: any | null;
  PropertyDescriptors?: Array<ExportedPropertyDescriptor> | null;
  ReflectedTrafficSequence?: TrafficSequenceData;
  ReflectedWorkflowText?: string | null;
  Reflection?: ExportedReflectionData;
  RelatedTrafficTemplate?: string | null;
  RelatedTrafficVariables?: Array<VariableData> | null;
  RelatedTrafficWorkflowText?: string | null;
  RuleDescription?: string | null;
  RuleDescriptionUniqueName?: string | null;
  RuleParameters?: Array<RuleParameterData> | null;
  RuleType?: RuleTypeEnum;
  RuleUniqueID?: string | null;
  RunWorkflowBeforeFuzz?: boolean;
  ServerFrameworks?: Array<ServerFrameworkData> | null;
  Severity?: SeverityEnum;
  SourceCode?: string | null;
  State?: FindingStateEnum;
  TrafficSequence?: TrafficSequenceData;
  TrafficTemplateDefinition?: ExportedTrafficTemplateDefinitionSource;
  UniqueID?: string;
  WorkflowParameters?: Array<WorkflowParameterData> | null;
  WorkflowText?: string | null;
}
